#YAML configuration file that holds the parameters for different components of your data pipeline.

# Specifies the root directory for all artifacts.
artifacts_root: artifacts

#Contains parameters related to data ingestion, including source URL, local data file, and directories for unzipping.
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sriramsripada20s/cardfraudml/blob/main/data_zip/sampled_creditdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#Holds settings for data validation, such as the root directory, paths for unzipped data, and a status file.
data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/sampled_creditdata.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#Includes details for data transformation, like the root directory and the path to the transformed data.
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts//data_validation/sampled_creditdata.csv

#Defines parameters for model training, including the paths for training and test data and the model file name.
model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

#Contains settings for model evaluation, such as the paths for test data, the trained model, metric storage
model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

#They're set up to specify paths and settings for each stage, making it easier to maintain and configure the pipeline as needed